-- Healcare Database SQL Dump

SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+00:00';
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `diseases` (
  `slug` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `icon` varchar(50) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `description` text,
  `eat` text,
  `limit_food` text,
  `symptoms` text,
  `causes` text,
  `prevention` text,
  `overview` text,
  `risk_factors` text,
  `monitoring` text,
  `daily` text,
  `urgent` text,
  `source` text,
  PRIMARY KEY (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE TABLE `diseases`;
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('tim-mach', 'Bệnh tim mạch', '♡', 'rose', 'Ưu tiên chế độ ăn ít muối, nhiều rau và chất béo không bão hòa; cần cá nhân hóa theo bệnh tim.', '[\"Rau củ, đậu và ngũ cốc nguyên hạt\",\"Cá và đạm nạc chế biến nhẹ\",\"Món tươi, nêm nhạt\"]', '[\"Thực phẩm nhiều muối\",\"Mỡ động vật và đồ chiên rán\",\"Rượu bia nếu bác sĩ yêu cầu hạn chế\"]', '[\"Đau hoặc nặng ngực\",\"Khó thở, mệt bất thường\",\"Hồi hộp, choáng hoặc phù chân\"]', '[\"Tăng huyết áp, mỡ máu cao, hút thuốc hoặc ít vận động\",\"Đái tháo đường, thừa cân và tiền sử gia đình\"]', '[\"Không hút thuốc, hạn chế rượu bia\",\"Theo dõi huyết áp, mỡ máu và đường huyết\",\"Vận động phù hợp, ngủ đủ và ăn giảm muối\"]', 'Bệnh tim mạch là nhóm bệnh ảnh hưởng đến tim và mạch máu. Mức độ và cách điều trị rất khác nhau giữa từng người.', '[\"Tăng huyết áp, mỡ máu hoặc đường huyết cao\",\"Hút thuốc, ít vận động, thừa cân\",\"Tiền sử gia đình\"]', '[\"Huyết áp, mỡ máu và đường huyết\",\"Cân nặng, mức vận động và triệu chứng\",\"Lịch khám tim mạch theo bác sĩ\"]', '[\"Dùng thuốc đúng giờ, không tự ngừng thuốc\",\"Ăn giảm muối, vận động theo khả năng\",\"Ghi lại triệu chứng bất thường\"]', '[\"Đau ngực dữ dội hoặc kéo dài\",\"Khó thở đột ngột, vã mồ hôi\",\"Yếu liệt một bên, méo miệng, nói khó\"]', 'https://www.who.int/health-topics/cardiovascular-diseases/');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('tieu-duong', 'Tiểu đường type 2', '◒', 'mint', 'Ưu tiên chất xơ, tinh bột nguyên hạt và kiểm soát khẩu phần.', '[\"Rau xanh, đậu và ngũ cốc nguyên hạt\",\"Cá, trứng, thịt nạc không chiên\",\"Trái cây nguyên miếng với khẩu phần vừa phải\"]', '[\"Nước ngọt, trà sữa, bánh kẹo\",\"Nước ép trái cây\",\"Tinh bột tinh chế ăn quá nhiều\"]', '[\"Khát và tiểu nhiều\",\"Mệt mỏi, nhìn mờ\",\"Vết thương lâu lành hoặc tê bì chân tay\"]', '[\"Đề kháng insulin và yếu tố di truyền\",\"Thừa cân, ít vận động và chế độ ăn dư năng lượng\"]', '[\"Duy trì cân nặng và vận động đều đặn\",\"Hạn chế đồ uống có đường, ăn nhiều chất xơ\",\"Theo dõi đường huyết theo hướng dẫn\"]', 'Tiểu đường là bệnh mạn tính làm đường huyết tăng kéo dài. Kiểm soát tốt giúp giảm nguy cơ ảnh hưởng đến tim, mắt, thận và thần kinh.', '[\"Thừa cân, ít vận động\",\"Gia đình có người mắc bệnh\",\"Tăng huyết áp hoặc từng tiểu đường thai kỳ\"]', '[\"Đường huyết theo kế hoạch\",\"Mắt, thận, bàn chân và huyết áp\",\"HbA1c theo lịch bác sĩ\"]', '[\"Không tự bỏ bữa hoặc tự đổi thuốc\",\"Kiểm tra bàn chân, chăm sóc da\",\"Chuẩn bị cách xử trí hạ đường huyết theo hướng dẫn\"]', '[\"Lơ mơ, co giật hoặc không thể ăn uống\",\"Khó thở, nôn nhiều, đau bụng\",\"Đường huyết bất thường không cải thiện\"]', 'https://www.who.int/news-room/fact-sheets/detail/diabetes');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('tang-huyet-ap', 'Tăng huyết áp', '♡', 'peach', 'Ưu tiên thực phẩm ít muối, nhiều rau quả và gia vị tự nhiên.', '[\"Rau củ quả tươi, ưu tiên hấp\\/luộc\",\"Cá, đậu phụ, thịt gia cầm bỏ da\",\"Chanh, gừng, tỏi\"]', '[\"Đồ muối chua và nước dùng mặn\",\"Thịt chế biến sẵn, đồ hộp\",\"Món nhiều dầu mỡ\"]', '[\"Thường không có dấu hiệu rõ\",\"Có thể đau đầu, chóng mặt hoặc hồi hộp\",\"Triệu chứng nặng có thể liên quan biến cố tim mạch\"]', '[\"Di truyền, tuổi tác và một số bệnh nền\",\"Ăn nhiều muối, ít vận động, thừa cân hoặc stress kéo dài\"]', '[\"Nêm nhạt, giảm đồ chế biến sẵn\",\"Đo huyết áp định kỳ\",\"Duy trì vận động và dùng thuốc đúng chỉ định\"]', 'Tăng huyết áp là tình trạng áp lực trong mạch máu cao dai dẳng. Nhiều người không có triệu chứng, vì vậy đo huyết áp đúng cách rất quan trọng.', '[\"Tuổi, tiền sử gia đình\",\"Ăn nhiều muối, ít vận động, thừa cân\",\"Bệnh thận, tiểu đường hoặc stress\"]', '[\"Đo huyết áp ở thời điểm cố định\",\"Ghi lại số đo và triệu chứng\",\"Kiểm tra thận, tim và mắt theo chỉ định\"]', '[\"Dùng thuốc đều, không tự ngừng\",\"Giảm muối và thực phẩm chế biến sẵn\",\"Đo lại khi có triệu chứng bất thường\"]', '[\"Đau ngực hoặc khó thở\",\"Đau đầu dữ dội kèm yếu liệt\\/nói khó\",\"Nhìn mờ hoặc lú lẫn đột ngột\"]', 'https://www.who.int/health-topics/hypertension');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('mo-mau', 'Mỡ máu cao', '◉', 'lavender', 'Giảm chất béo bão hòa, tăng chất xơ hòa tan và chất béo tốt.', '[\"Yến mạch, đậu, rau củ giàu chất xơ\",\"Cá béo nếu phù hợp\",\"Dầu thực vật dùng vừa đủ\"]', '[\"Mỡ động vật, da và nội tạng\",\"Đồ chiên rán, bánh ngọt công nghiệp\",\"Thịt đỏ ăn quá thường xuyên\"]', '[\"Thường không có triệu chứng\",\"Có thể phát hiện qua xét nghiệm máu\",\"Biến cố tim mạch là dấu hiệu nghiêm trọng\"]', '[\"Di truyền, thừa cân hoặc ít vận động\",\"Ăn nhiều chất béo bão hòa và chất béo chuyển hóa\"]', '[\"Tăng rau, đậu và chất xơ hòa tan\",\"Giảm đồ chiên, mỡ động vật\",\"Kiểm tra mỡ máu theo lịch\"]', 'Mỡ máu cao là sự thay đổi bất lợi của cholesterol hoặc triglyceride. Bệnh thường không gây triệu chứng nhưng có thể làm tăng nguy cơ tim mạch.', '[\"Chế độ ăn nhiều chất béo bão hòa\",\"Thừa cân, ít vận động\",\"Di truyền, tiểu đường hoặc bệnh tuyến giáp\"]', '[\"Xét nghiệm mỡ máu theo lịch\",\"Cân nặng, huyết áp và đường huyết\",\"Đánh giá nguy cơ tim mạch tổng thể\"]', '[\"Ăn thêm rau, đậu và chất xơ\",\"Vận động đều đặn theo khả năng\",\"Dùng thuốc nếu được kê, không tự bỏ\"]', '[\"Đau ngực, khó thở, vã mồ hôi\",\"Yếu liệt hoặc nói khó đột ngột\"]', 'https://www.who.int/health-topics/cardiovascular-diseases/');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('than-man', 'Bệnh thận mạn', '✦', 'sky', 'Nhu cầu đạm, muối, kali và nước cần được cá nhân hóa theo giai đoạn bệnh.', '[\"Món tươi, nêm nhạt theo hướng dẫn\",\"Khẩu phần đạm đúng chỉ định\",\"Trao đổi bác sĩ trước khi đổi chế độ ăn\"]', '[\"Tự ý dùng thực phẩm bổ sung\",\"Nước hầm xương cô đặc và đồ chế biến sẵn\",\"Thực phẩm giàu kali\\/phốt pho khi chưa được hướng dẫn\"]', '[\"Giai đoạn sớm có thể không rõ triệu chứng\",\"Phù, mệt, thay đổi lượng nước tiểu\",\"Buồn nôn hoặc ngứa khi bệnh nặng\"]', '[\"Thường liên quan tiểu đường hoặc tăng huyết áp kéo dài\",\"Một số bệnh thận, thuốc và yếu tố di truyền\"]', '[\"Kiểm soát đường huyết và huyết áp\",\"Không tự dùng thuốc giảm đau hoặc thực phẩm bổ sung kéo dài\",\"Khám và xét nghiệm theo lịch bác sĩ\"]', 'Bệnh thận mạn tiến triển khi thận giảm khả năng lọc chất thải và dịch thừa. Chế độ ăn phụ thuộc giai đoạn bệnh, xét nghiệm và việc có lọc máu hay không.', '[\"Tiểu đường và tăng huyết áp\",\"Bệnh thận hoặc tim mạch\",\"Một số thuốc và tiền sử gia đình\"]', '[\"Creatinine\\/eGFR và xét nghiệm nước tiểu\",\"Kali, natri, phốt pho theo chỉ định\",\"Cân nặng, phù và lượng nước tiểu\"]', '[\"Không tự áp dụng chế độ nhiều đạm hoặc nhiều nước\",\"Không tự dùng thuốc bổ, thuốc nam\",\"Tuân thủ lịch xét nghiệm và lọc máu nếu có\"]', '[\"Khó thở, phù tăng nhanh\",\"Đau ngực, lơ mơ hoặc yếu nhiều\",\"Tiểu rất ít hoặc không tiểu\"]', 'https://www.who.int/news-room/fact-sheets/detail/kidney-disease');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('gout', 'Gút', '◇', 'rose', 'Uống đủ nước theo chỉ định và hạn chế thực phẩm, đồ uống có thể làm tăng acid uric.', '[\"Rau củ đa dạng\",\"Sữa ít béo nếu phù hợp\",\"Nước lọc và món luộc\\/hấp\"]', '[\"Bia, rượu và nước ngọt có đường\",\"Nội tạng, thịt đỏ quá nhiều\",\"Hải sản hoặc nước dùng cô đặc khi bác sĩ yêu cầu hạn chế\"]', '[\"Đau dữ dội, sưng nóng đỏ một khớp\",\"Thường gặp ở ngón chân cái nhưng không chỉ ở đó\",\"Đợt đau có thể tái phát\"]', '[\"Acid uric tăng do cơ địa, bệnh nền hoặc giảm thải qua thận\",\"Rượu bia, đồ uống có đường và một số thực phẩm có thể làm tăng nguy cơ\"]', '[\"Giữ cân nặng phù hợp và uống nước theo chỉ định\",\"Hạn chế bia rượu, nước ngọt\",\"Dùng thuốc dự phòng đúng hướng dẫn\"]', 'Gút liên quan đến tình trạng acid uric tăng và các đợt viêm khớp cấp. Việc điều trị cần phối hợp thuốc, ăn uống và theo dõi xét nghiệm.', '[\"Tiền sử gia đình, bệnh thận\",\"Rượu bia, thừa cân\",\"Một số thuốc hoặc chế độ ăn đặc thù\"]', '[\"Acid uric theo chỉ định\",\"Số lần và vị trí các đợt đau\",\"Chức năng thận và thuốc đang dùng\"]', '[\"Uống nước theo hướng dẫn\",\"Không tự ngừng thuốc hạ acid uric\",\"Giảm rượu bia và đồ uống có đường\"]', '[\"Sốt kèm khớp sưng nóng đỏ\",\"Đau dữ dội không giảm hoặc không thể vận động\",\"Tiểu rất ít hoặc đau hông lưng\"]', 'https://www.who.int/health-topics/noncommunicable-diseases');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('gan-nhiem-mo', 'Gan nhiễm mỡ', '◐', 'gold', 'Giảm đường tự do, rượu bia và năng lượng dư thừa; ưu tiên vận động phù hợp.', '[\"Rau, đậu, cá và ngũ cốc nguyên hạt\",\"Trái cây nguyên miếng\",\"Món hấp, luộc, nướng nhẹ\"]', '[\"Rượu bia\",\"Nước ngọt, trà sữa và bánh ngọt\",\"Đồ chiên rán nhiều dầu\"]', '[\"Thường không có triệu chứng\",\"Mệt hoặc khó chịu vùng bụng phải\",\"Xét nghiệm men gan hoặc siêu âm bất thường\"]', '[\"Thừa cân, kháng insulin hoặc rối loạn mỡ máu\",\"Rượu bia và chế độ ăn dư đường\\/năng lượng\"]', '[\"Giảm cân từ từ nếu cần\",\"Hạn chế rượu bia và nước ngọt\",\"Tăng vận động và tái khám khi được hẹn\"]', 'Gan nhiễm mỡ là tình trạng mỡ tích tụ trong gan. Nguyên nhân có thể liên quan chuyển hóa, rượu bia hoặc thuốc nên cần đánh giá cụ thể.', '[\"Thừa cân, tiểu đường, mỡ máu cao\",\"Uống rượu bia\",\"Ít vận động hoặc ăn dư năng lượng\"]', '[\"Men gan và xét nghiệm chuyển hóa\",\"Siêu âm hoặc kiểm tra chuyên khoa khi cần\",\"Cân nặng và vòng eo\"]', '[\"Giảm cân từ từ nếu bác sĩ khuyến nghị\",\"Hạn chế rượu bia, nước ngọt\",\"Ăn vừa đủ và vận động đều\"]', '[\"Vàng da, lơ mơ hoặc chảy máu bất thường\",\"Đau bụng dữ dội hoặc nôn kéo dài\",\"Bụng to nhanh hoặc phù tăng\"]', 'https://www.who.int/health-topics/noncommunicable-diseases');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('da-day', 'Viêm/đau dạ dày', '☼', 'cream', 'Ăn đúng bữa, khẩu phần vừa phải và theo dõi thực phẩm làm bạn khó chịu.', '[\"Món mềm, ấm, ít dầu\",\"Cháo, súp và rau củ nấu chín\",\"Chia nhỏ bữa nếu phù hợp\"]', '[\"Rượu bia, cà phê khi làm tăng triệu chứng\",\"Món rất cay hoặc quá chua\",\"Ăn quá no hoặc bỏ bữa kéo dài\"]', '[\"Đau hoặc nóng rát vùng thượng vị\",\"Đầy bụng, buồn nôn\",\"Ợ hơi hoặc ăn nhanh no\"]', '[\"Nhiễm vi khuẩn H. pylori hoặc dùng một số thuốc\",\"Rượu bia, hút thuốc và yếu tố kích thích có thể làm nặng triệu chứng\"]', '[\"Ăn đúng bữa, tránh tác nhân làm bạn đau\",\"Không tự dùng thuốc kéo dài\",\"Khám khi đau kéo dài, nôn hoặc đi ngoài phân đen\"]', 'Đau hoặc viêm dạ dày có nhiều nguyên nhân. Cần khám khi triệu chứng kéo dài để tìm nguyên nhân và dùng thuốc đúng.', '[\"H. pylori, thuốc giảm đau chống viêm\",\"Rượu bia, hút thuốc\",\"Bữa ăn thất thường hoặc yếu tố kích thích\"]', '[\"Mức độ đau, nôn và khả năng ăn uống\",\"Phân đen hoặc dấu hiệu mất máu\",\"Kết quả xét nghiệm khi bác sĩ chỉ định\"]', '[\"Ăn đúng bữa, phần nhỏ nếu cần\",\"Không tự dùng thuốc giảm đau kéo dài\",\"Tránh yếu tố làm triệu chứng tăng\"]', '[\"Nôn ra máu hoặc đi ngoài phân đen\",\"Đau bụng dữ dội, choáng\",\"Sụt cân hoặc khó nuốt kéo dài\"]', 'https://www.who.int/health-topics/noncommunicable-diseases');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('trao-nguoc', 'Trào ngược dạ dày', '↟', 'peach', 'Ăn khẩu phần nhỏ và tránh nằm ngay sau khi ăn.', '[\"Món ít dầu, ít cay\",\"Rau củ nấu chín\",\"Ăn chậm và theo dõi yếu tố kích phát\"]', '[\"Ăn quá no vào buổi tối\",\"Đồ chiên, bạc hà, cà phê nếu kích triệu chứng\",\"Nằm ngay sau bữa ăn\"]', '[\"Ợ nóng, ợ chua\",\"Nóng rát sau xương ức\",\"Ho hoặc khàn tiếng về đêm\"]', '[\"Cơ vòng thực quản yếu hoặc thoát vị hoành\",\"Thừa cân, ăn quá no và nằm ngay sau bữa ăn\"]', '[\"Ăn khẩu phần nhỏ, không nằm ngay sau ăn\",\"Giảm cân nếu thừa cân\",\"Theo dõi và tránh thực phẩm kích triệu chứng\"]', 'Trào ngược xảy ra khi dịch dạ dày đi ngược lên thực quản, gây khó chịu và đôi khi ảnh hưởng giấc ngủ.', '[\"Ăn quá no, nằm ngay sau ăn\",\"Thừa cân, hút thuốc\",\"Một số thức ăn hoặc thuốc kích triệu chứng\"]', '[\"Tần suất và thời điểm triệu chứng\",\"Khả năng nuốt, cân nặng và giấc ngủ\",\"Tái khám nếu không cải thiện\"]', '[\"Ăn phần nhỏ, không nằm ngay sau ăn\",\"Kê cao đầu khi được hướng dẫn\",\"Tránh tác nhân riêng của mỗi người\"]', '[\"Đau ngực mới xuất hiện hoặc dữ dội\",\"Khó nuốt tăng dần, nôn ra máu\",\"Sụt cân không rõ nguyên nhân\"]', 'https://www.who.int/health-topics/noncommunicable-diseases');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('tao-bon', 'Táo bón', '❋', 'mint', 'Tăng chất xơ từ từ, uống đủ nước nếu không bị hạn chế dịch.', '[\"Rau xanh, trái cây nguyên miếng\",\"Yến mạch và các loại đậu\",\"Vận động nhẹ theo khả năng\"]', '[\"Ít vận động và uống quá ít nước\",\"Đồ ăn siêu chế biến ít chất xơ\",\"Tự dùng thuốc nhuận tràng kéo dài\"]', '[\"Phân cứng, rặn nhiều\",\"Cảm giác đi chưa hết\",\"Đầy bụng hoặc đau bụng nhẹ\"]', '[\"Thiếu chất xơ, uống ít nước hoặc ít vận động\",\"Một số thuốc, bệnh lý hoặc thay đổi thói quen sinh hoạt\"]', '[\"Tăng chất xơ từ từ\",\"Uống đủ nước nếu không bị hạn chế dịch\",\"Tạo thói quen đi vệ sinh và vận động nhẹ\"]', 'Táo bón là tình trạng đi tiêu khó, thưa hoặc phân cứng. Nguyên nhân thường liên quan thói quen nhưng đôi khi cần loại trừ bệnh lý.', '[\"Ít chất xơ, ít nước, ít vận động\",\"Thay đổi sinh hoạt hoặc một số thuốc\",\"Tuổi cao hoặc bệnh nền\"]', '[\"Số lần đi tiêu và hình dạng phân\",\"Đau bụng, nôn hoặc chướng bụng\",\"Mức đáp ứng khi thay đổi thói quen\"]', '[\"Tăng chất xơ từ từ\",\"Uống đủ nước nếu không bị hạn chế\",\"Đi bộ và không nhịn đi tiêu\"]', '[\"Đau bụng dữ dội, nôn hoặc bụng trướng\",\"Có máu trong phân hoặc sụt cân\",\"Táo bón mới xuất hiện kéo dài ở người lớn tuổi\"]', 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('beo-phi', 'Thừa cân/béo phì', '◌', 'lavender', 'Tập trung vào khẩu phần, chất lượng bữa ăn và mục tiêu giảm cân an toàn.', '[\"Rau củ chiếm phần lớn đĩa\",\"Đạm nạc và ngũ cốc nguyên hạt\",\"Nước lọc thay đồ uống có đường\"]', '[\"Đồ uống có đường\",\"Ăn vặt theo thói quen\",\"Nhịn ăn cực đoan hoặc chế độ thiếu chất\"]', '[\"Tăng cân hoặc vòng eo tăng\",\"Dễ mệt khi vận động\",\"Ngáy to hoặc buồn ngủ ban ngày ở một số người\"]', '[\"Nạp năng lượng kéo dài cao hơn nhu cầu cơ thể\",\"Di truyền, giấc ngủ, thuốc và môi trường sống\"]', '[\"Ăn chậm, theo dõi khẩu phần\",\"Ưu tiên thực phẩm ít chế biến\",\"Đặt mục tiêu giảm cân an toàn cùng chuyên gia\"]', 'Thừa cân và béo phì là tình trạng tích tụ mỡ quá mức có thể ảnh hưởng đến tim mạch, chuyển hóa, khớp và chất lượng sống.', '[\"Năng lượng nạp vào cao hơn nhu cầu\",\"Ít vận động, thiếu ngủ\",\"Di truyền, thuốc và môi trường sống\"]', '[\"Cân nặng, vòng eo và huyết áp\",\"Đường huyết, mỡ máu theo chỉ định\",\"Khả năng vận động và giấc ngủ\"]', '[\"Đặt mục tiêu nhỏ, tránh nhịn ăn cực đoan\",\"Tăng vận động phù hợp\",\"Theo dõi khẩu phần và đồ uống có đường\"]', '[\"Khó thở nhiều, đau ngực\",\"Ngất hoặc phù tăng nhanh\",\"Triệu chứng bất thường khi tập luyện\"]', 'https://www.who.int/health-topics/obesity');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('loang-xuong', 'Loãng xương', '✧', 'sky', 'Quan tâm đến đạm, canxi, vitamin D và vận động theo tư vấn chuyên môn.', '[\"Sữa\\/sản phẩm thay thế phù hợp\",\"Cá, trứng và đậu phụ\",\"Rau xanh đa dạng\"]', '[\"Tự dùng liều cao thực phẩm bổ sung\",\"Rượu bia và hút thuốc\",\"Ăn thiếu năng lượng kéo dài\"]', '[\"Thường không có triệu chứng sớm\",\"Đau lưng hoặc giảm chiều cao\",\"Gãy xương sau va chạm nhẹ\"]', '[\"Tuổi tác, thay đổi nội tiết hoặc tiền sử gia đình\",\"Thiếu canxi\\/vitamin D, ít vận động và hút thuốc\"]', '[\"Bảo đảm đạm và canxi theo tư vấn\",\"Vận động chịu sức nặng phù hợp\",\"Phòng ngã và kiểm tra mật độ xương khi cần\"]', 'Loãng xương làm xương yếu và dễ gãy hơn. Bệnh có thể diễn tiến âm thầm cho đến khi xảy ra gãy xương.', '[\"Tuổi cao, mãn kinh hoặc tiền sử gia đình\",\"Thiếu canxi\\/vitamin D, ít vận động\",\"Hút thuốc, rượu bia hoặc dùng một số thuốc\"]', '[\"Mật độ xương khi được chỉ định\",\"Tiền sử té ngã và gãy xương\",\"Canxi, vitamin D theo tư vấn\"]', '[\"Phòng ngã trong nhà\",\"Vận động chịu sức nặng phù hợp\",\"Không tự dùng liều cao thực phẩm bổ sung\"]', '[\"Đau dữ dội sau té ngã\",\"Không thể đứng hoặc cử động chi\",\"Tê yếu bất thường\"]', 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet');
INSERT INTO `diseases` (`slug`, `name`, `icon`, `color`, `description`, `eat`, `limit_food`, `symptoms`, `causes`, `prevention`, `overview`, `risk_factors`, `monitoring`, `daily`, `urgent`, `source`) VALUES ('thieu-mau', 'Thiếu máu thiếu sắt', '✚', 'rose', 'Cần xác định nguyên nhân và dùng sắt theo chỉ định, không tự bổ sung kéo dài.', '[\"Thịt nạc, cá, trứng và đậu\",\"Rau xanh kết hợp thực phẩm giàu vitamin C\",\"Bữa ăn đa dạng\"]', '[\"Tự mua thuốc sắt không kiểm tra nguyên nhân\",\"Uống trà\\/cà phê sát bữa giàu sắt\",\"Bỏ bữa kéo dài\"]', '[\"Mệt, yếu, da nhợt\",\"Chóng mặt hoặc khó thở khi gắng sức\",\"Tim đập nhanh hoặc đau đầu\"]', '[\"Thiếu sắt do ăn thiếu, mất máu hoặc hấp thu kém\",\"Một số bệnh mạn tính và nguyên nhân khác cần xét nghiệm\"]', '[\"Ăn đa dạng và bổ sung theo chỉ định\",\"Tìm nguyên nhân khi thiếu máu tái diễn\",\"Không tự dùng sắt liều cao kéo dài\"]', 'Thiếu máu là tình trạng cơ thể không có đủ hồng cầu hoặc hemoglobin để vận chuyển oxy. Thiếu sắt chỉ là một trong nhiều nguyên nhân.', '[\"Ăn thiếu sắt, mất máu hoặc hấp thu kém\",\"Bệnh mạn tính, thai kỳ hoặc nhu cầu tăng\",\"Một số bệnh cần được xét nghiệm tìm nguyên nhân\"]', '[\"Công thức máu và xét nghiệm sắt khi cần\",\"Mức độ mệt, khó thở và chóng mặt\",\"Đáp ứng với điều trị được kê\"]', '[\"Ăn đa dạng, kết hợp nguồn sắt và vitamin C\",\"Không tự uống sắt liều cao\",\"Tái khám nếu thiếu máu tái diễn\"]', '[\"Khó thở khi nghỉ, đau ngực hoặc ngất\",\"Chảy máu nhiều\",\"Mệt tăng nhanh hoặc tim đập rất nhanh\"]', 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet');

CREATE TABLE IF NOT EXISTS `foods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `type` varchar(100) DEFAULT NULL,
  `benefits` text,
  `image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE TABLE `foods`;
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (1, 'Rau cải xanh', '', '[]', 'assets/images/food-rau-cu.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (2, 'Bông cải xanh', '', '[]', 'assets/images/food-rau-cu.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (3, 'Cá hấp gừng', '', '[]', 'assets/images/recipe-ca-hap-gung.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (4, 'Ức gà bỏ da', '', '[]', 'assets/images/food-uc-ga.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (5, 'Đậu phụ', '', '[]', 'assets/images/food-dau-phu.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (6, 'Yến mạch nguyên hạt', '', '[]', 'assets/images/food-ngu-coc.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (7, 'Gạo lứt', '', '[]', 'assets/images/food-ngu-coc.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (8, 'Táo', '', '[]', 'assets/images/food-tao.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (9, 'Bưởi', '', '[]', 'assets/images/food-buoi.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (10, 'Chuối', '', '[]', 'assets/images/food-chuoi.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (11, 'Cam', '', '[]', 'assets/images/food-cam.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (12, 'Sữa chua không đường', '', '[]', 'assets/images/food-sua-chua.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (13, 'Hạt không muối', '', '[]', 'assets/images/food-hat-khong-muoi.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (14, 'Nước lọc', '', '[]', 'assets/images/food-nuoc-loc.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (15, 'Trà nhạt không đường', '', '[]', 'assets/images/food-tra-nhat.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (16, 'Nước ngọt có đường', '', '[]', 'assets/images/food-nuoc-ngot.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (17, 'Bánh quy ngọt', '', '[]', 'assets/images/food-banh-quy-ngot.png');
INSERT INTO `foods` (`id`, `name`, `type`, `benefits`, `image`) VALUES (18, 'Khoai tây chiên', '', '[]', 'assets/images/food-khoai-tay-chien.png');

CREATE TABLE IF NOT EXISTS `recipes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `meal` varchar(100) DEFAULT NULL,
  `time` varchar(100) DEFAULT NULL,
  `difficulty` varchar(100) DEFAULT NULL,
  `description` text,
  `ingredients` text,
  `steps` text,
  `suitable_for` text,
  `youtube_query` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE TABLE `recipes`;
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (1, 'Cháo yến mạch cá hồi', 'Bữa sáng', '20 phút', 'Dễ', 'Mềm, dễ ăn và giàu đạm; nêm nhạt, không dùng nước dùng đóng gói.', '[\"yến mạch\",\"cá hồi\",\"gừng\",\"rau xanh\"]', '[\"Rửa sạch cá và hấp với vài lát gừng.\",\"Nấu yến mạch với nước đến khi mềm.\",\"Gỡ cá, cho vào cháo và nêm nhạt.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\"]', 'cháo yến mạch cá hồi nêm nhạt', 'assets/images/recipe-chao-yen-mach-ca-hoi.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (2, 'Trứng hấp rau củ', 'Bữa sáng', '15 phút', 'Rất dễ', 'Món mềm, dễ nhai, có thể dùng cùng một phần nhỏ tinh bột.', '[\"trứng\",\"cà rốt\",\"nấm\",\"rau xanh\"]', '[\"Đánh trứng với nước ấm.\",\"Thêm rau củ cắt nhỏ.\",\"Hấp lửa vừa đến khi trứng vừa chín.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\"]', 'trứng hấp rau củ mềm dễ ăn', 'assets/images/recipe-trung-hap-rau-cu.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (3, 'Cá hấp gừng', 'Bữa trưa', '30 phút', 'Dễ', 'Nhiều đạm, dễ ăn; có thể điều chỉnh gia vị theo hướng dẫn bác sĩ.', '[\"cá tươi\",\"gừng\",\"hành lá\",\"chanh\"]', '[\"Làm sạch cá, khứa nhẹ hai mặt.\",\"Xếp gừng lên cá và hấp chín.\",\"Dùng chanh, hành và rau thơm thay cho nhiều muối.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\",\"gan-nhiem-mo\"]', 'cá hấp gừng ít muối cách làm', 'assets/images/recipe-ca-hap-gung.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (4, 'Cá hấp rau thơm', 'Bữa trưa', '25 phút', 'Dễ', 'Thanh đạm, ít muối, giàu axit béo omega-3 hỗ trợ tim mạch.', '[\"cá phi lê\",\"thì là\",\"hành hoa\",\"tiêu nhạt\"]', '[\"Làm sạch cá và ướp tiêu nhẹ.\",\"Lót thì là, hành hoa dưới đáy đĩa hấp.\",\"Hấp cách thủy 15 phút đến khi chín mềm.\"]', '[\"tim-mach\",\"tang-huyet-ap\",\"than-man\"]', 'cá hấp rau thơm thanh đạm', 'assets/images/recipe-ca-hap-rau-thom.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (5, 'Canh rau củ thịt nạc', 'Bữa trưa', '30 phút', 'Dễ', 'Nhiều rau, ít mỡ; phù hợp bữa gia đình khi nêm vừa phải.', '[\"bí đỏ\",\"cà rốt\",\"thịt nạc\",\"hành\"]', '[\"Sơ chế rau củ và thịt nạc.\",\"Nấu thịt chín rồi thêm rau củ.\",\"Nêm nhạt, dùng khi còn ấm.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\",\"da-day\"]', 'canh rau củ thịt nạc ít muối', 'assets/images/recipe-canh-rau-cu-thit-nac.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (6, 'Đậu phụ sốt nấm nhạt', 'Bữa trưa', '15 phút', 'Rất dễ', 'Món đạm thực vật nhẹ bụng, phù hợp khi cần giảm món chiên.', '[\"đậu phụ\",\"nấm\",\"gừng\",\"hành lá\"]', '[\"Áp chảo đậu phụ với ít dầu hoặc hấp.\",\"Xào nấm với gừng.\",\"Cho đậu vào, thêm chút nước và nêm nhạt.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\",\"gout\"]', 'đậu phụ sốt nấm nhạt dễ làm', 'assets/images/recipe-dau-phu-sot-nam.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (7, 'Đậu phụ hấp rau củ', 'Bữa tối', '20 phút', 'Rất dễ', 'Thanh mát, giàu xơ và đạm thực vật dễ tiêu hóa.', '[\"đậu phụ non\",\"đậu Hà Lan\",\"ngô ngọt\",\"cà rốt\"]', '[\"Cắt đậu hũ thành khối vừa ăn.\",\"Rải rau củ xung quanh đĩa.\",\"Hấp chín 10 phút, dùng cùng nước tương nhạt.\"]', '[\"gan-nhiem-mo\",\"beo-phi\",\"tang-huyet-ap\"]', 'đậu phụ hấp rau củ thanh nhiệt', 'assets/images/recipe-dau-phu-hap-rau-cu.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (8, 'Rau xanh và dưa chuột', 'Bữa tối', '10 phút', 'Rất dễ', 'Món rau tươi nhẹ nhàng, dùng cùng gia vị tự nhiên và ít muối.', '[\"rau xanh\",\"dưa chuột\",\"chanh\",\"dầu ô liu\"]', '[\"Rửa sạch rau và dưa chuột.\",\"Cắt vừa ăn, để ráo nước.\",\"Trộn với chanh và một ít dầu ô liu.\"]', '[\"tieu-duong\",\"tang-huyet-ap\",\"mo-mau\",\"tao-bon\",\"beo-phi\"]', 'salad rau xanh dưa chuột sốt chanh', 'assets/images/recipe-rau-xanh-dua-chuot.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (9, 'Rau củ hấp phần nhỏ', 'Bữa tối', '15 phút', 'Rất dễ', 'Bổ sung chất xơ hòa tan giúp kiểm soát đường huyết và huyết áp.', '[\"súp lơ\",\"cà rốt\",\"đậu bắp\",\"su hào\"]', '[\"Rửa sạch và cắt miếng vừa ăn.\",\"Hấp cách thủy khoảng 8-10 phút.\",\"Dùng nóng để giữ nguyên vitamin tự nhiên.\"]', '[\"tieu-duong\",\"than-man\",\"mo-mau\"]', 'rau củ luộc hấp chấm kho quẹt ít mặn', 'assets/images/recipe-rau-cu-hap-phan-nho.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (10, 'Thịt nạc cuộn rau xanh', 'Bữa tối', '25 phút', 'Dễ', 'Đầy đủ dinh dưỡng đạm - xơ mà không chứa dầu mỡ dư thừa.', '[\"thịt nạc thăn\",\"xà lách\",\"rau thơm\",\"dưa leo\"]', '[\"Luộc chín thịt nạc với chút gừng.\",\"Thái lát mỏng.\",\"Cuộn cùng rau sống tươi sạch.\"]', '[\"tieu-duong\",\"thieu-mau\",\"beo-phi\"]', 'thịt nạc luộc cuốn rau sống ngon', 'assets/images/recipe-thit-nac-cuon-rau-xanh.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (11, 'Khoai lang nướng mềm', 'Bữa phụ', '35 phút', 'Dễ', 'Bữa phụ đơn giản; vẫn cần tính vào tổng lượng tinh bột trong ngày.', '[\"khoai lang\"]', '[\"Rửa sạch và chọc vài lỗ trên vỏ.\",\"Nướng đến khi mềm.\",\"Ăn khẩu phần vừa phải, không thêm đường.\"]', '[\"tieu-duong\",\"tao-bon\",\"beo-phi\"]', 'khoai lang nướng mềm không dầu', 'assets/images/recipe-khoai-lang-nuong-mem.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (12, 'Sữa chua trái cây không đường', 'Bữa phụ', '5 phút', 'Rất dễ', 'Bữa phụ nhanh; kiểm tra dị ứng sữa và không thêm siro đường.', '[\"sữa chua không đường\",\"táo\",\"dâu\",\"hạt không muối\"]', '[\"Rửa sạch và cắt trái cây.\",\"Cho sữa chua vào bát.\",\"Thêm lượng nhỏ trái cây và hạt.\"]', '[\"tieu-duong\",\"mo-mau\",\"tao-bon\"]', 'sữa chua trái cây không đường bữa phụ', 'assets/images/recipe-sua-chua-trai-cay.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (13, 'Cháo bí đỏ thịt nạc', 'Bữa tối', '30 phút', 'Dễ', 'Món mềm, ấm, dễ ăn; nên điều chỉnh khẩu phần theo nhu cầu cá nhân.', '[\"bí đỏ\",\"gạo\",\"thịt nạc\",\"gừng\"]', '[\"Nấu gạo và bí đỏ đến mềm.\",\"Thêm thịt nạc băm đã hấp chín.\",\"Nêm nhạt và dùng ấm.\"]', '[\"da-day\",\"trao-nguoc\",\"loang-xuong\"]', 'cháo bí đỏ thịt nạc mềm dễ ăn', 'assets/images/recipe-chao-bi-do-thit-nac.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (14, 'Yến mạch cá hồi rau xanh', 'Bữa sáng', '25 phút', 'Dễ', 'Bữa sáng hoàn hảo giàu canxi, sắt và omega-3 cho cả gia đình.', '[\"yến mạch cán dẹt\",\"cá hồi tươi\",\"rau cải bó xôi\",\"dầu mè\"]', '[\"Nấu yến mạch với nước dùng thanh.\",\"Cho cá hồi xé nhỏ và rau thái sợi vào.\",\"Khuấy đều 3 phút và tắt bếp.\"]', '[\"tim-mach\",\"loang-xuong\",\"thieu-mau\"]', 'yến mạch nấu cá hồi rau chân vịt', 'assets/images/recipe-yen-mach-ca-hoi-rau-xanh.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (15, 'Cá hấp rau thơm không muối', 'Bữa trưa', '25 phút', 'Dễ', 'Món hấp ít dầu; vẫn cần kiểm soát khẩu phần và lượng muối theo tình trạng tim, gan của từng người.', '[\"cá trắng\",\"gừng\",\"hành lá\",\"rau thơm\",\"chanh\"]', '[\"Làm sạch cá và đặt lên xửng hấp.\",\"Thêm gừng, hành lá, rau thơm rồi hấp chín.\",\"Dùng chanh và rau thơm thay cho nước chấm mặn.\"]', '[\"tim-mach\",\"gan-nhiem-mo\"]', 'cá hấp rau thơm không muối tốt cho tim mạch', 'assets/images/recipe-ca-hap-rau-thom.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (16, 'Đậu phụ hấp rau củ', 'Bữa trưa', '20 phút', 'Rất dễ', 'Món nhẹ, không dùng nội tạng hay nước dùng cô đặc; người bệnh gút cần trao đổi bác sĩ về khẩu phần đạm và lượng nước.', '[\"đậu phụ\",\"bắp cải\",\"cà rốt\",\"gừng\",\"chanh\"]', '[\"Cắt đậu phụ và rau củ thành miếng vừa ăn.\",\"Hấp rau củ gần chín rồi thêm đậu phụ.\",\"Dùng chanh, gừng và lượng muối nhỏ theo hướng dẫn.\"]', '[\"gout\"]', 'đậu phụ hấp rau củ nhạt cho người bệnh gút', 'assets/images/recipe-dau-phu-hap-rau-cu.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (17, 'Yến mạch cá hồi rau xanh', 'Bữa sáng', '20 phút', 'Dễ', 'Ưu tiên cách nấu đơn giản và không đường; tổng năng lượng vẫn cần được cá nhân hóa.', '[\"yến mạch\",\"cá hồi\",\"rau xanh\",\"gừng\"]', '[\"Hấp cá hồi với gừng rồi gỡ nhỏ.\",\"Nấu yến mạch với nước đến khi mềm.\",\"Thêm cá và rau xanh, không thêm đường hoặc nước dùng nhiều muối.\"]', '[\"gan-nhiem-mo\"]', 'yến mạch cá hồi rau xanh không đường', 'assets/images/recipe-yen-mach-ca-hoi-rau-xanh.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (18, 'Thịt nạc cuộn rau xanh', 'Bữa trưa', '25 phút', 'Dễ', 'Có thể bổ sung đạm và sắt từ thực phẩm; thiếu máu vẫn cần tìm nguyên nhân và dùng thuốc theo chỉ định.', '[\"thịt nạc\",\"rau cải\",\"cà rốt\",\"chanh\"]', '[\"Trải rau cải, đặt một lượng nhỏ thịt nạc vào giữa.\",\"Cuộn lại và hấp chín kỹ.\",\"Dùng cùng rau củ và thực phẩm giàu vitamin C theo khẩu phần phù hợp.\"]', '[\"thieu-mau\"]', 'thịt nạc cuộn rau xanh hấp mềm', 'assets/images/recipe-thit-nac-cuon-rau-xanh.png');
INSERT INTO `recipes` (`id`, `title`, `meal`, `time`, `difficulty`, `description`, `ingredients`, `steps`, `suitable_for`, `youtube_query`, `image`) VALUES (19, 'Rau củ hấp phần nhỏ', 'Bữa trưa', '20 phút', 'Rất dễ', 'Đây chỉ là nền món ít muối; loại rau, khẩu phần, kali, phốt pho, đạm và lượng nước phải theo giai đoạn bệnh và xét nghiệm.', '[\"bắp cải\",\"súp lơ\",\"cà rốt\",\"chanh\"]', '[\"Rửa và cắt rau củ thành miếng vừa ăn.\",\"Hấp chín mềm, không dùng nước hầm cô đặc.\",\"Chỉ thêm gia vị theo lượng muối, kali và nước được bác sĩ cho phép.\"]', '[\"than-man\"]', 'rau củ hấp nêm nhạt cho bệnh thận', 'assets/images/recipe-rau-cu-hap-phan-nho.png');

CREATE TABLE IF NOT EXISTS `medical_contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `type` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `address` text,
  `working_hours` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE TABLE `medical_contacts`;
INSERT INTO `medical_contacts` (`id`, `name`, `type`, `phone`, `address`, `working_hours`) VALUES (1, 'Bệnh viện Chợ Rẫy', '', '', '', '');
INSERT INTO `medical_contacts` (`id`, `name`, `type`, `phone`, `address`, `working_hours`) VALUES (2, 'Bệnh viện Bạch Mai', '', '02438689711', '', '');
INSERT INTO `medical_contacts` (`id`, `name`, `type`, `phone`, `address`, `working_hours`) VALUES (3, 'Bệnh viện Nhân dân 115', '', '', '', '');

CREATE TABLE IF NOT EXISTS `crm_contacts` (
  `id` varchar(50) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `message` text,
  `source` varchar(50) DEFAULT 'website',
  `status` varchar(50) DEFAULT 'new',
  `priority` varchar(50) DEFAULT 'normal',
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


