<?php
$contacts = $knowledge->contacts();
$success = $_SESSION['contact_success'] ?? '';
$error = $_SESSION['contact_error'] ?? '';
unset($_SESSION['contact_success'], $_SESSION['contact_error']);
?>
<section class="page-intro"><span class="eyebrow">KẾT NỐI CHĂM SÓC THẬT</span><h1>Liên hệ bác sĩ</h1><p>Healcare giúp bạn tìm đúng kênh liên hệ của cơ sở y tế. AI chỉ hỗ trợ thông tin, còn chẩn đoán và điều trị cần nhân viên y tế trực tiếp.</p></section>
<section class="emergency-banner"><div class="emergency-number">115</div><div><h2>Tình huống khẩn cấp</h2><p>Gọi 115 hoặc đến khoa Cấp cứu gần nhất khi có đau ngực, khó thở, yếu liệt, lơ mơ, ngất hoặc chảy máu nhiều.</p></div><a class="button emergency-button" href="tel:115">Gọi 115</a></section>
<section class="contact-layout">
    <div><div class="section-heading contact-heading"><div><span class="eyebrow">CƠ SỞ Y TẾ THAM KHẢO</span><h2>Chọn nơi bạn muốn liên hệ</h2></div></div><div class="medical-contact-list"><?php foreach ($contacts as $contact): ?><article class="medical-contact-card"><div class="hospital-mark">⚕</div><div class="medical-contact-content"><h3><?= e($contact['name']) ?></h3><p class="contact-area"><?= e($contact['area']) ?></p><p><?= e($contact['specialties']) ?></p><small><?= e($contact['note']) ?></small><div class="contact-links"><?php if ($contact['phone']): ?><a href="tel:<?= e($contact['phone']) ?>">☎ <?= e($contact['phone']) ?></a><?php endif; ?><a href="<?= e($contact['website']) ?>" target="_blank" rel="noopener">Website chính thức ↗</a></div></div></article><?php endforeach; ?></div></div>
    <div class="contact-form-wrap"><span class="eyebrow">YÊU CẦU ĐƯỢC LIÊN HỆ</span><h2>Để lại thông tin</h2><p>Chỉ gửi thông tin tối thiểu cần thiết. Không nhập bệnh án chi tiết hoặc thông tin nhạy cảm vào biểu mẫu này.</p><?php if ($success): ?><div class="form-alert success"><?= e($success) ?></div><?php endif; ?><?php if ($error): ?><div class="form-alert error"><?= e($error) ?></div><?php endif; ?><form class="contact-form" method="post" action="<?= url('contact') ?>"><label>Họ tên<input name="name" required placeholder="Nguyễn Văn A"></label><label>Số điện thoại<input name="phone" type="tel" required placeholder="09xx xxx xxx"></label><label>Nội dung cần hỗ trợ<textarea name="message" rows="5" required placeholder="Tôi muốn được hướng dẫn đặt lịch khám..."></textarea></label><label class="consent"><input type="checkbox" required> Tôi đồng ý để Healcare sử dụng thông tin này cho yêu cầu liên hệ.</label><button class="button" type="submit">Gửi yêu cầu liên hệ <span>→</span></button></form></div>
</section>
